language: crystal
sudo: required

matrix:
  include:
  - os: linux
    dist: trusty
    install:
    - sudo apt-get update
    - sudo apt-get install -qy crystal llvm-3.5-dev libclang-3.5-dev build-essential zlib1g-dev libedit-dev libssl-dev
  - os: osx
    install:
    - brew update
    - brew install crystal-lang llvm
